services:
    integralservice_doctrine_encrypt.orm_subscriber:
        class: IntegralService\DoctrineEncryptBundle\Subscribers\DoctrineEncryptSubscriber
        arguments: ["@annotation_reader", "%integralservice_doctrine_encrypt.encryptor_class_name%", "%integralservice_doctrine_encrypt.secret_key%"]
        tags:
            -  { name: doctrine.event_subscriber }
    integralservice_doctrine_encrypt.subscriber:
        alias: integralservice_doctrine_encrypt.orm_subscriber
    integralservice_doctrine_encrypt.encryptor:
        class: IntegralService\DoctrineEncryptBundle\Services\Encryptor
        arguments:
            - "%integralservice_doctrine_encrypt.encryptor_class_name%"
            - "%integralservice_doctrine_encrypt.secret_key%"
